name: Get Pods Info

on:
  workflow_dispatch:   # run manually from Actions tab

jobs:
  pods-info:
    runs-on: [self-hosted, windows]   # your Windows runner with kubectl installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Get Pods Info
        shell: pwsh
        run: |
          Write-Output "=== Pods in All Namespaces ==="
          kubectl get pods -A -o wide
          
          Write-Output "=== Pod Details (first 50 lines) ==="
          kubectl describe pods -A | Select-Object -First 50
          
          Write-Output "=== Pod Events (last 20) ==="
          kubectl get events -A --sort-by=.metadata.creationTimestamp | Select-Object -Last 20
