name: Get Cluster & Pods Info22

on:
  workflow_dispatch:   # run manually from Actions tab

jobs:
  cluster-pods-info:
    runs-on: [self-hosted, windows]   # 👈 your Windows runner with kubectl installed & configured

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Cluster Info
        shell: pwsh
        run: |
          Write-Output "=== Cluster Info ==="
          kubectl cluster-info
          Write-Output "`n"

      - name: Show Nodes Info
        shell: pwsh
        run: |
          Write-Output "=== Nodes Info ==="
          kubectl get nodes -o wide
          Write-Output "`n"

      - name: Show Namespaces
        shell: pwsh
        run: |
          Write-Output "=== Namespaces ==="
          kubectl get ns
          Write-Output "`n"

      - name: Show Pods Info
        shell: pwsh
        run: |
          Write-Output "=== Pods in All Namespaces (wide) ==="
          kubectl get pods -A -o wide
          Write-Output "`n"

      - name: Show Pod Details (limited)
        shell: pwsh
        run: |
          Write-Output "=== Pod Details (first 50 lines) ==="
          kubectl describe pods -A | Select-Object -First 50
          Write-Output "`n"

      - name: Show Pod Events
        shell: pwsh
        run: |
          Write-Output "=== Pod Events (last 20) ==="
          kubectl get events -A --sort-by=.metadata.creationTimestamp | Select-Object -Last 20
          Write-Output "`n"
