name: Get Pods Info

on:
  workflow_dispatch:   # run manually from Actions tab

jobs:
  pods-info:
    runs-on: [self-hosted, windows]   # your Windows runner with kubectl installed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Get Pods Info
        shell: pwsh
        run: |
          Write-Output "=== Pods in All Namespaces ==="
          kubectl get pods -A -o wide
          
          Write-Output "=== Pod Details (describe, first 50 lines) ==="
          kubectl describe pods -A | Select-Object -First 50
          
          Write-Output "=== Pod Events (last 20) ==="
          kubectl get events -A --sort-by=.metadata.creationTimestamp | Select-Object -Last 20

      - name: Save Pods Info as Artifact
        shell: pwsh
        run: |
          kubectl get pods -A -o wide | Out-File pods-list.txt
          kubectl describe pods -A | Out-File pods-describe.txt
          

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pods-info
          path: |
            pods-list.txt
            pods-describe.txt
            pods-events.txt
